### ISSUE TITLE
[Bug] Multimedia keys not working

### ISSUE THREAD

**Issue by jcalado** [msvisser/qmk_firmware#18]
## Describe the Bug

Multimedia keys, F13-21 not working

## System Information

 - Keyboard:  Anne Pro
 - Operating system: Windows 10 with WSL2 (tested with linux as well, same result)
 - AVR GCC version: 5.4.0
 - ARM GCC version: arm-none-eabi-gcc (15:7-2018-q2-6) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
 - QMK Firmware version: 0.6.430
 - Any keyboard related software installed? 
No.

## Additional Context

Triggering `MO(2)` on the base layer lets me use the `RESET` key, but multimedia keys dont work, as well as the `F13` - `F21`.
Also tried moving `MO(2)` to other keys, same behavior.

**Comment by jcalado** [comment]
I also have a gist here with my keymap: https://gist.github.com/jcalado/985f580c98d8eca7704de06cf30190be

**Comment by jcalado** [comment]
Confirmed this is only an issue over bluetooth. While connected via USB everything works as expected.

**Comment by msvisser** [comment]
Hi there, it has been a really long time since I worked on this code. As far as I remember the firmware of the bluetooth chip in the Anne Pro only supports normal keyboard HID, so I don't think media keys are possible at all over bluetooth. For the F13-F21 keys I'm not sure, it seems like they should be supported, however this is probably a limitation of the firmware on the bluetooth chip. Since there is no custom firmware for the bluetooth chip, the only thing I can do is emulate the messages of the original Anne Pro firmware. I'm sorry I cannot help you much more.

**Comment by jcalado** [comment]
👍  Thanks for the fast reply.
Just wondering if it was a bug or I was doing something wrong.

Thank you for your work on this branch though, it gave new life to my og anne pro!
